[tool.poetry]
name = "convergence-nautobot"
version = "1.0.0"
description = "Nautobot instance for Convergence with apps"
authors = ["Convergence Team"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
# Nautobot will be installed from the base image
# Only declare the apps here
nautobot-device-onboarding = "^4.0.0"
nautobot-golden-config = "^2.6.0"
nautobot-device-lifecycle-mgmt = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
